# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'R-Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for R-Demo

  pod 'R.swift'

end
